export const CHECK_LOGIN = 'CHECK_LOGIN';
export const CHECK_LOGIN_FAILURE = 'CHECK_LOGIN_FAILURE';
export const CHECK_LOGIN_SUCCESS = 'CHECK_LOGIN_SUCCESS';

export const GET_USER_LOGIN = 'GET_USER_LOGIN';
export const GET_USER_LOGIN_SUCCESS = 'GET_USER_LOGIN_SUCCESS';
export const GET_USER_LOGIN_FAILURE = 'GET_USER_LOGIN_FAILURE';