export const UPDATE_USERNAME_INPUT_TEXT = 'UPDATE_USERNAME_INPUT_TEXT';
export const UPDATE_PASSWORD_INPUT_TEXT = 'UPDATE_PASSWORD_INPUT_TEXT';

export const CHECK_LOGIN = 'CHECK_LOGIN';
export const CHECK_LOGIN_FAILURE = 'CHECK_LOGIN_FAILURE';
export const CHECK_LOGIN_SUCCESS = 'CHECK_LOGIN_SUCCESS';

export const GET_USER_LOGIN = 'GET_USER_LOGIN';
export const GET_USER_LOGIN_SUCCESS = 'GET_USER_LOGIN_SUCCESS';
export const GET_USER_LOGIN_FAILURE = 'GET_USER_LOGIN_FAILURE';

export const LOG_OUT = 'LOG_OUT';

export const FETCH_LOHANG = 'FETCH_LOHANG';
export const FETCH_LOHANG_SUCCESS = 'FETCH_LOHANG_SUCCESS';
export const FETCH_LOHANG_FAILURE = 'FETCH_LOHANG_FAILURE';

export const SET_DATA_LOHANG = 'SET_DATA_LOHANG';
export const UPDATE_SOLUONG_RACHUYEN = 'UPDATE_SOLUONG_RACHUYEN';
export const UPDATE_SOLUONG_RACHUYEN_SUCCESS = 'UPDATE_SOLUONG_RACHUYEN_SUCCESS';
export const ADD_ACTION_TO_QUEUE = 'ADD_ACTION_TO_QUEUE';

export const CHANGE_CONNECTION_STATUS = 'CHANGE_CONNECTION_STATUS';
